name: Dependencies check

on:
  schedule:
    - cron: "17 16 * * *"
  workflow_dispatch:

env:
  RENOVATE_CONFIG_PATH: 'data/config/renovate.json'

jobs:
  renovate-dependencies:
    name: Renovate dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Renovate
        uses: renovatebot/github-action@v44.2.1
        with:
          configurationFile: ${{ env.RENOVATE_CONFIG_PATH }}
          token: ${{ secrets.RENOVATE_TOKEN }}
